DROP TABLE IF EXISTS Revisione_file CASCADE;
DROP TABLE IF EXISTS File_task CASCADE;
DROP TABLE IF EXISTS Commento_task CASCADE;
DROP TABLE IF EXISTS Membro_attivita CASCADE;
DROP TABLE IF EXISTS Attivita CASCADE;
DROP TABLE IF EXISTS Membro_progetto CASCADE;
DROP TABLE IF EXISTS Progetto CASCADE;
DROP TABLE IF EXISTS Utente CASCADE;

DROP TYPE IF EXISTS Tipo_attivita CASCADE;
DROP TYPE IF EXISTS Stato_attivita CASCADE;

CREATE TABLE Utente (
	id_utente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email VARCHAR(50) NOT NULL UNIQUE,
	password_utente VARCHAR(20) NOT NULL,
	nome VARCHAR(15) NOT NULL,
	cognome VARCHAR(15) NOT NULL
);

CREATE TABLE Progetto (
	id_progetto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	descrizione TEXT,
	id_creatore INTEGER NOT NULL REFERENCES Utente(id_utente)
);

CREATE TABLE Membro_progetto (
	id_prog INTEGER NOT NULL REFERENCES Progetto(id_progetto),
	id_membro INTEGER NOT NULL REFERENCES Utente(id_utente),
	PRIMARY KEY(id_prog, id_membro)
);

CREATE TYPE Tipo_attivita AS ENUM (
	'Sviluppo',
	'Studio',
	'Documentazione'
);

CREATE TYPE Stato_attivita AS ENUM (
	'Nuova',
	'Presa_in_carico',
	'Finita'
);

CREATE TABLE Attivita (
    id_attivita INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_prog INT NOT NULL REFERENCES Progetto(id_progetto),
    titolo VARCHAR(30) NOT NULL,
    descrizione TEXT,
    scadenza DATE,
    tipo Tipo_attivita,
	stato Stato_attivita DEFAULT 'Nuova',
    id_creatore INT NOT NULL REFERENCES utente(id_utente),
    creata_il TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT progetto_attivita_unica UNIQUE (id_prog, id_attivita)
);

CREATE TABLE Membro_attivita (
	id_task INT NOT NULL REFERENCES Attivita(id_attivita),
	id_membro INT NOT NULL REFERENCES Utente(id_utente),
	PRIMARY KEY (id_task, id_membro)
);

CREATE TABLE Commento_task (
	id_commento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_task INT NOT NULL REFERENCES Attivita(id_attivita),
	id_membro INT NOT NULL REFERENCES Utente(id_utente),
	testo VARCHAR(100),
	scritto_il TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE File_task (
	id_file INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_task INT NOT NULL REFERENCES Attivita(id_attivita),
	nome_file VARCHAR(30) NOT NULL,
	estensione VARCHAR(10) NOT NULL
);

CREATE TABLE Revisione_file (
    id_revisione INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_file_rev INT NOT NULL REFERENCES File_task(id_file) ON DELETE CASCADE,
    versione INT NOT NULL DEFAULT 1 CHECK (versione > 0),
    id_autore INT NOT NULL REFERENCES Utente(id_utente),
    data_modifica TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nota_descrittiva VARCHAR(40),
    contenuto BYTEA NOT NULL,
    CONSTRAINT file_versione_unica UNIQUE (id_file_rev, versione)
);

-- 1. Creiamo la funzione che calcola la versione
CREATE OR REPLACE FUNCTION calcola_nuova_versione()
RETURNS TRIGGER AS $$
BEGIN
    -- Cerca il numero massimo di versione per QUEL file specifico.
    -- Se non trova nulla (primo inserimento), restituisce 0. Poi somma 1.
    SELECT COALESCE(MAX(versione), 0) + 1
    INTO NEW.versione
    FROM Revisione_file
    WHERE id_file_rev = NEW.id_file_rev;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_incrementa_versione
BEFORE INSERT ON Revisione_file
FOR EACH ROW
EXECUTE FUNCTION calcola_nuova_versione();


--CARICAMENTO DATI--
-- 1. UTENTI
INSERT INTO Utente (email, password_utente, nome, cognome) VALUES 
('mario.rossi@studenti.unina.it', 'password123', 'Mario', 'Rossi'),     -- ID 1
('luigi.verdi@studenti.unina.it', 'password123', 'Luigi', 'Verdi'),     -- ID 2
('anna.bianchi@docenti.unina.it', 'docente123', 'Anna', 'Bianchi'),     -- ID 3
('giulia.neri@studenti.unina.it', 'password123', 'Giulia', 'Neri');     -- ID 4

-- 2. PROGETTI
INSERT INTO Progetto (nome, descrizione, id_creatore) VALUES 
('Sistema Gestione Esami', 'Applicativo per la registrazione dei voti OOBD', 1), -- ID 1
('Sito Web Dipartimento', 'Restyling portale ingegneria', 3);                    -- ID 2

-- 3. MEMBRI DEI PROGETTI
INSERT INTO Membro_progetto (id_prog, id_membro) VALUES 
(1, 1), (1, 2), (1, 4), -- Mario, Luigi e Giulia lavorano al progetto 1
(2, 3), (2, 1);         -- Anna e Mario lavorano al progetto 2

-- 4. ATTIVITÀ (Varie tipologie e stati per testare i filtri e il report)
INSERT INTO Attivita (id_prog, titolo, descrizione, scadenza, tipo, stato, id_creatore) VALUES 
(1, 'Progettazione DB', 'Creare lo schema SQL', '2026-10-15', 'Sviluppo', 'Finita', 1),             -- ID 1 (Prog 1)
(1, 'Scrittura Classi Entity', 'Mappare le tabelle in Java', '2026-10-20', 'Sviluppo', 'Presa_in_carico', 1), -- ID 2 (Prog 1)
(1, 'Manuale Utente', 'Scrivere la documentazione', '2026-11-01', 'Documentazione', 'Nuova', 1),    -- ID 3 (Prog 1)
(2, 'Analisi Requisiti', 'Studio dei competitor', '2026-10-10', 'Studio', 'Finita', 3),             -- ID 4 (Prog 2)
(2, 'Sviluppo Frontend', 'Creare la home in HTML', '2026-10-25', 'Sviluppo', 'Presa_in_carico', 3); -- ID 5 (Prog 2)

-- 5. ASSEGNAZIONE MEMBRI ALLE ATTIVITÀ
INSERT INTO Membro_attivita (id_task, id_membro) VALUES 
(1, 1), (1, 2), -- Mario e Luigi hanno finito il DB
(2, 4),         -- Giulia sta scrivendo le Entity
(4, 3),         -- Anna ha fatto l'analisi
(5, 1);         -- Mario sta sviluppando il frontend

-- 6. COMMENTI
INSERT INTO Commento_task (id_task, id_membro, testo) VALUES 
(2, 4, 'Ho quasi finito la classe Utente.java, domani pusho il codice.'),
(5, 3, 'Ricordati di usare il logo ufficiale del dipartimento Mario!');

-- 7. FILE DI CODICE (Solo per le attività di Sviluppo, come da traccia)
INSERT INTO File_task (id_task, nome_file, estensione) VALUES 
(1, 'Database', 'txt'),   -- ID 1 (Appartiene all'attività 1)
(2, 'Utente', 'txt');    -- ID 2 (Appartiene all'attività 2)
