DROP TABLE IF EXISTS Revisione_file CASCADE;
DROP TABLE IF EXISTS File_task CASCADE;
DROP TABLE IF EXISTS Commento_task CASCADE;
DROP TABLE IF EXISTS Membro_attivita CASCADE;
DROP TABLE IF EXISTS Attivita CASCADE;
DROP TABLE IF EXISTS Membro_progetto CASCADE;
DROP TABLE IF EXISTS Progetto CASCADE;
DROP TABLE IF EXISTS Utente CASCADE;

DROP TYPE IF EXISTS Tipo_attivita CASCADE;
DROP TYPE IF EXISTS Stato_attivita CASCADE;

CREATE TABLE Utente (
	id_utente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email VARCHAR(50) NOT NULL UNIQUE,
	password_utente VARCHAR(20) NOT NULL,
	nome VARCHAR(15) NOT NULL,
	cognome VARCHAR(15) NOT NULL
);

CREATE TABLE Progetto (
	id_progetto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	descrizione TEXT,
	id_creatore INTEGER NOT NULL REFERENCES Utente(id_utente)
);

CREATE TABLE Membro_progetto (
	id_prog INTEGER NOT NULL REFERENCES Progetto(id_progetto),
	id_membro INTEGER NOT NULL REFERENCES Utente(id_utente),
	PRIMARY KEY(id_prog, id_membro)
);

CREATE TYPE Tipo_attivita AS ENUM (
	'Sviluppo',
	'Studio',
	'Documentazione'
);

CREATE TYPE Stato_attivita AS ENUM (
	'Nuova',
	'Presa_in_carico',
	'Finita'
);

CREATE TABLE Attivita (
    id_attivita INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_prog INT NOT NULL REFERENCES Progetto(id_progetto),
    titolo VARCHAR(30) NOT NULL,
    descrizione TEXT,
    scadenza DATE,
    tipo Tipo_attivita,
	stato Stato_attivita DEFAULT 'Nuova',
    id_creatore INT NOT NULL REFERENCES utente(id_utente),
    creata_il TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT progetto_attivita_unica UNIQUE (id_prog, id_attivita)
);

CREATE TABLE Membro_attivita (
	id_task INT NOT NULL REFERENCES Attivita(id_attivita),
	id_membro INT NOT NULL REFERENCES Utente(id_utente),
	PRIMARY KEY (id_task, id_membro)
);

CREATE TABLE Commento_task (
	id_commento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_task INT NOT NULL REFERENCES Attivita(id_attivita),
	id_membro INT NOT NULL REFERENCES Utente(id_utente),
	testo VARCHAR(100),
	scritto_il TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE File_task (
	id_file INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id_task INT NOT NULL REFERENCES Attivita(id_attivita),
	nome_file VARCHAR(30) NOT NULL,
	estensione VARCHAR(10) NOT NULL,
	dimensione BIGINT,
	contenuto BYTEA NOT NULL
);

CREATE TABLE Revisione_file (
	id_file_rev INT NOT NULL REFERENCES File_task(id_file),
	id_task INT NOT NULL REFERENCES Attivita(id_attivita),
	versione INT NOT NULL DEFAULT 1 CHECK (versione>0)
);